[default]
src = 'contracts'
test = 'test'
out = 'artifacts'
libs = ['node_modules', '../../node_modules']
verbosity = 2
fuzz_runs = 256
fuzz_max_global_rejects = 100000000

[ci]
src = 'contracts'
test = 'test'
out = 'artifacts'
libs = ['node_modules', '../../node_modules']
verbosity = 2
fuzz_max_global_rejects = 100000000
fuzz_runs = 2500
