#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# get the current branch
current_branch=$(git rev-parse --abbrev-ref HEAD)

# get the list of files changed in the current branch
files_changed=$(git diff --name-only $current_branch)

# check if the files changed include packages/greenfield-app
if [[ $files_changed == *"packages/greenfield-app"* ]]; then
  yarn build
  exit 0
else
  exit 0
fi
