name: Circulating Supply Deployment Cron Job

on: push

env:
  CI: true
  ALCHEMY_API_KEYS: ${{ secrets.ALCHEMY_API_KEYS }}
  BNB_RPC_URLS: ${{ secrets.BNB_RPC_URLS }}

jobs:
  Circulating-Supply:
    name: Circulating Supply Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Checkout to circulating-supply branch
        uses: actions/checkout@v3
        with:
          ref: circulating-supply

      - name: "Delete node modules"
        run: |
          rm -rf node_modules
          rm -rf packages/utils/node_modules

      - name: "yarn install"
        run: yarn

      - name: "Build hardhat"
        run: cd packages/hardhat && yarn export

      - name: "Log version of ts-node used"
        run: yarn ts-node --version

      - name: "Log version of typescript used"
        run: yarn tsc --version

      - name: Run script
        run: yarn circulating-supply

      - name: Make pr comment
        uses: mshick/add-pr-comment@v2
        with:
          message: "Update circulating supply"

      - name: Push
        run: git push
