name: Circulating Supply Development Cron Job

on: push

jobs:
  Circulating-Supply:
    name: Circulating Supply Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Checkout to circulating-supply branch
        uses: actions/checkout@v3
        with:
          ref: circulating-supply
      - name: "yarn install"
        run: yarn install
      - name: Build tsc file using ts -b
        run: cd packages/utils && tsc -b
        env:
          ALCHEMY_API_KEYS: ${{ secrets.ALCHEMY_API_KEYS }}
          BNB_RPC_URLS: ${{ secrets.BNB_RPC_URLS }}
      - name: serve dist folder using node
        run: node packages/utils/dist/circulating-supply/circulating-supply
      - name: Make PR Comment
        uses: mshick/add-pr-comment@v2
        with:
          message: "Update circulating supply"
      - name: Push
        run: git push
