name: Deploy Release

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - 'release/*' # Push events to every tag not containing /

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: curl -X POST -d {} https://api.vercel.com/v1/integrations/deploy/$DEPLOY_HOOK
    env:
      DEPLOY_HOOK: ${{secrets.RELEASE_DEPLOY_HOOK}}