name: Prettier Action
description: Automatically runs prettier on all your changes.

author: Amir <amir1jab@gmail.com>

on: push

runs:
  using: "composite"
  steps:
    - name: Prettify code!
      shell: bash
      run: ./prettify.sh

