name: Prettier Action

on: push

jobs:
  Prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Prettify code!
        shell: bash
        run: >-
        PATH=$(cd $GITHUB_ACTION_PATH; npm bin):$PATH
        ${{ github.action_path }}/entrypoint.sh

