name: Prettify

# This action works with pushes on all branches
on: push

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: canastro/copy-file-action@master
        name: "copy env file"
        with:
          source: .env.example
          target: .env
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: "yarn install"
        run: yarn add prettier -W 
      - name: "pretify"
        run: yarn pretify