name: Prettier Action
description: Automatically runs prettier on all your changes.

author: Amir <amir1jab@gmail.com>

runs:
  using: "composite"
  steps:
    - name: Prettify code!
      shell: bash
      run: >-
        PATH=$(cd $GITHUB_ACTION_PATH; npm bin):$PATH
        ${{ github.action_path }}/prettify.sh

branding:
  icon: "award"
  color: "green"