# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [16.x]
      fail-fast:
        false
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
      - uses: actions/checkout@v2
      - uses: canastro/copy-file-action@master
        name: "copy env file"
        with:
          source: .env.example
          target: .env
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
        # - uses: borales/actions-yarn@v3.0.0
        name: "yarn install"
      - run: yarn install
        # with:
        #   cmd: install # will run `yarn install` command
        name: "yarn install"
      - run: yarn build
        # - uses: borales/actions-yarn@v3.0.0
        #   name: "build"
        #   with:
        #     cmd: app:build # will run `yarn app:build` command
        env:
          CI: true
        # - uses: borales/actions-yarn@v3.0.0
        name: "run tests"
      - run: yarn test
