# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Foundry Tests

on:
  push:
    paths:
      - packages/foundry/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: cd packages/foundry && forge build
        id: build

      - name: Run tests
        run: cd packages/foundry && forge test
        env:
          FOUNDRY_PROFILE: ci
          RPC_URL: ${{secrets.RPC_URL}}
          FORKING_RPC_URL: ${{secrets.RPC_URL}}
