# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Solidity Test Coverage

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    env:
      NODE_OPTIONS: "--max-old-space-size=8500"
      # Coverage requires extra memory:
      # See: https://github.com/sc-forks/solidity-coverage/blob/master/docs/faq.md#running-out-of-memory

    steps:
      - uses: actions/checkout@v2
      - uses: canastro/copy-file-action@master
        name: "copy env file"
        with:
          source: .env.example
          target: .env
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: "yarn install"
        run: yarn install
      - name: "yarn build"
        run: yarn build
        env:
          CI: true
      - name: "solidity coverage"
        run: "yarn coverage"
