# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Forge Tests

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: canastro/copy-file-action@master
        name: "copy env file"
        with:
          source: .env.example
          target: .env

      - uses: borales/actions-yarn@v3.0.0
        name: "yarn install"
        with:
          cmd: install # will run `yarn install` command

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: logging
        run: ls && cd packages && ls && cd hardhat && ls && ls lib

      - name: Run Forge build
        run: cd packages/hardhat && forge build
        id: build

      - name: Run tests
        run: yarn test:forge
        env:
          FOUNDRY_PROFILE: ci
          RPC_URL: ${{secrets.RPC_URL}}
