---
name: "Foundry Tests and Coverage"

on:
  push:
    paths:
      - packages/foundry/**
  workflow_dispatch:

env:
  VERCEL_ORG_ID: "${{ secrets.VERCEL_ORG_ID }}"
  VERCEL_PROJECT_ID: "${{ secrets.VERCEL_FOUNDRY_PROJECT_ID }}"

jobs:
  Tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: "Yarn install"
        run: cd packages/foundry && yarn

      - name: Run Forge build
        run: cd packages/foundry && forge build
        id: build

      - name: Run tests
        run: cd packages/foundry && forge test --sender 0x1804c8AB1F12E6bbf3894d4083f33e07309d1f38 -vvv
        env:
          FOUNDRY_PROFILE: ci
          RPC_URL: ${{secrets.RPC_URL}}
          FORKING_RPC_URL: ${{secrets.RPC_URL}}

  Publish-Coverage:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - name: Install ubuntu dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libxml2-utils
          sudo apt-get install libz3-dev libz3-4
          sudo apt-get install lcov
          sudo apt-get install libcppunit-dev
          python -m pip install pip --upgrade
          python -m pip install lcov_cobertura

      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: "Yarn install"
        run: cd packages/foundry && yarn

      - name: Make PR Comment
        uses: mshick/add-pr-comment@v2
        with:
          message: "Generating link to coverage report ..."

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          cd packages/foundry
          forge --version
          forge build --sizes
        id: build

      - name: Generate coverage report
        run: |
          cd packages/foundry
          utils/coverage.sh

        env:
          FOUNDRY_PROFILE: ci
          RPC_URL: ${{secrets.RPC_URL}}
          FORKING_RPC_URL: ${{secrets.RPC_URL}}

      - name: "Install Vercel CLI"
        run: "npm install --global vercel@latest"

      - name: "Pull Vercel Environment Information"
        run: "vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}"

      - name: "Build Project Artifacts"
        run: "vercel build --token=${{ secrets.VERCEL_TOKEN }}"

      - name: "Deploy Project Artifacts to Vercel"
        run: |
          vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} > deployment-url.txt
          echo "vercel_preview_url=$(cat deployment-url.txt)" >> $GITHUB_OUTPUT
        id: vercel_deploy

      - name: Make PR Comment
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            ### Link to coverage report:
            [${{ steps.vercel_deploy.outputs.vercel_preview_url}}](${{ steps.vercel_deploy.outputs.vercel_preview_url}})
